package com.deepak.exchangeops.service;

import com.deepak.exchangeops.domain.Alert;
import com.deepak.exchangeops.domain.AlertRule;
import com.deepak.exchangeops.domain.AlertRuleType;
import com.deepak.exchangeops.domain.AlertStatus;
import com.deepak.exchangeops.domain.MarketEvent;
import com.deepak.exchangeops.domain.Symbol;
import com.deepak.exchangeops.domain.Venue;
import com.deepak.exchangeops.dto.AlertResponse;
import com.deepak.exchangeops.mapper.AlertMapper;
import com.deepak.exchangeops.repository.AlertRepository;
import com.deepak.exchangeops.repository.AlertRuleRepository;
import java.math.BigDecimal;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Evaluates newly generated synthetic market events against enabled
 * single-event alert rules.
 *
 * <p>Historical and stateful rule types are intentionally skipped
 * until their required event-window or venue-state logic is
 * implemented.
 */
@Service
public class LiveAlertEvaluator {

  private static final Logger log =
      LoggerFactory.getLogger(LiveAlertEvaluator.class);

  private final AlertRuleRepository ruleRepository;
  private final AlertRepository alertRepository;
  private final AlertMapper alertMapper;
  private final SimpMessagingTemplate messagingTemplate;
  private final Clock clock;

  public LiveAlertEvaluator(
      AlertRuleRepository ruleRepository,
      AlertRepository alertRepository,
      AlertMapper alertMapper,
      SimpMessagingTemplate messagingTemplate,
      Clock clock) {

    this.ruleRepository = ruleRepository;
    this.alertRepository = alertRepository;
    this.alertMapper = alertMapper;
    this.messagingTemplate = messagingTemplate;
    this.clock = clock;
  }

  /**
   * Evaluates and publishes alerts generated by one persisted event.
   *
   * @return persisted alert responses created for the event
   */
  @Transactional
  public List<AlertResponse> evaluate(
      MarketEvent event,
      Venue venue,
      Symbol symbol) {

    return ruleRepository
        .findByEnabledTrueOrderByNameAsc()
        .stream()
        .filter(rule -> matches(rule, event))
        .filter(
            rule ->
                !alertRepository.existsByRuleIdAndEventId(
                    rule.getId(),
                    event.getId()))
        .map(
            rule ->
                createPersistAndPublish(
                    rule,
                    event,
                    venue,
                    symbol))
        .toList();
  }

  private boolean matches(
      AlertRule rule,
      MarketEvent event) {

    BigDecimal threshold = rule.getThreshold();

    if (threshold == null) {
      return false;
    }

    return switch (rule.getRuleType()) {
      case LATENCY_THRESHOLD ->
          BigDecimal.valueOf(event.getProcessingLatencyMs())
                  .compareTo(threshold)
              >= 0;

      case VOLUME_SPIKE ->
          BigDecimal.valueOf(event.getQuantity())
                  .compareTo(threshold)
              >= 0;

      case PRICE_DEVIATION,
          SEQUENCE_GAP,
          STALE_FEED,
          VENUE_STATUS_CHANGE -> false;
    };
  }

  private AlertResponse createPersistAndPublish(
      AlertRule rule,
      MarketEvent event,
      Venue venue,
      Symbol symbol) {

    Instant detectedAt = Instant.now(clock);

    String title =
        rule.getName()
            + " triggered on "
            + symbol.getTicker();

    String explanation =
        explanation(rule, event);

    Alert alert =
        new Alert(
            UUID.randomUUID(),
            rule.getId(),
            event.getId(),
            venue.getId(),
            symbol.getId(),
            rule.getSeverity(),
            AlertStatus.OPEN,
            title,
            explanation,
            null,
            detectedAt);

    Alert saved = alertRepository.save(alert);

    AlertResponse response =
        alertMapper.toResponse(
            saved,
            rule,
            venue.getCode(),
            symbol.getTicker(),
            null);

    messagingTemplate.convertAndSend(
        "/topic/alerts",
        response);

    log.info(
        "Synthetic alert {} created by rule {} for event {}",
        saved.getId(),
        rule.getId(),
        event.getId());

    return response;
  }

  private String explanation(
      AlertRule rule,
      MarketEvent event) {

    return switch (rule.getRuleType()) {
      case LATENCY_THRESHOLD ->
          "Synthetic detection. Rule \""
              + rule.getName()
              + "\" matched sequence "
              + event.getSequenceNumber()
              + " because processing latency "
              + event.getProcessingLatencyMs()
              + " ms met or exceeded threshold "
              + rule.getThreshold()
              + " ms.";

      case VOLUME_SPIKE ->
          "Synthetic detection. Rule \""
              + rule.getName()
              + "\" matched sequence "
              + event.getSequenceNumber()
              + " because quantity "
              + event.getQuantity()
              + " met or exceeded threshold "
              + rule.getThreshold()
              + ".";

      default ->
          "Synthetic detection generated by rule \""
              + rule.getName()
              + "\".";
    };
  }
}
